#!/bin/sh
#
# This test measures the performance of various read-tree
# and status operations.  It is primarily interested in
# the algorithmic costs of index operations and recursive
# tree traversal -- and NOT disk I/O on thousands of files.

test_description="Tests performance of read-tree"

. ./perf-lib.sh

test_perf_default_repo

# If the test repo was generated by ./repos/many-files.sh
# then we know something about the data shape and branches,
# so we can isolate testing to the ballast-related commits
# and setup sparse-checkout so we don't have to populate
# the ballast files and directories.
#
# Otherwise, we make some general assumptions about the
# repo and consider the entire history of the current
# branch to be the ballast.

test_expect_success "setup repo" '
	if git rev-parse --verify refs/heads/p0006-ballast^{commit}
	then
		echo Assuming synthetic repo from many-files.sh
		git branch br_base            master
		git branch br_ballast         p0006-ballast
		git config --local core.sparsecheckout 1
		cat >.git/info/sparse-checkout <<-EOF
		/*
		!ballast/*
		EOF
	else
		echo Assuming non-synthetic repo...
		git branch br_base            $(git rev-list HEAD | tail -n 1)
		git branch br_ballast         HEAD
	fi &&
	git checkout -q br_ballast &&
	nr_files=$(git ls-files | wc -l)
'

test_perf "read-tree status br_ballast ($nr_files)" '
	git read-tree HEAD &&
	git status
'

test_lazy_prereq UNTRACKED_CACHE '
	{ git update-index --test-untracked-cache; ret=$?; } &&
	test $ret -ne 1
'

if ! test_have_prereq UNTRACKED_CACHE; then
	skip_all='This system does not support untracked cache'
	test_done
fi

test_expect_success "setup untracked cache" '
	git config core.untrackedcache true
'

test_perf "read-tree status br_ballast ($nr_files)" '
	git read-tree HEAD &&
	git status
'

test_lazy_prereq WATCHMAN '
	type watchman
'

if ! test_have_prereq WATCHMAN; then
	skip_all='This system does not have watchman installed'
	test_done
fi

test_expect_success "setup watchman and the query-fsmonitor hook" '
	watchman watch "$PWD" &&
	test_when_finished watchman watch-del "$PWD" &&
	git init --template=../templates &&
	mkdir .git/hooks &&
	cp .git/hooks-disabled/query-fsmonitor.sample .git/hooks/query-fsmonitor &&
	git config core.fsmonitor true &&
	git config core.untrackedcache false
'

test_perf "read-tree status br_ballast ($nr_files)" '
	git read-tree HEAD &&
	git status
'

test_expect_success "setup untracked cache on top of watchman" '
	git config core.untrackedcache true
'

test_perf "read-tree status br_ballast ($nr_files)" '
	git read-tree HEAD &&
	git status
'

test_done
